# docker-compose.yml example

version: '3.9'
services:

  timebase:
    image: "finos/timebase-ce-server:latest"
    oom_kill_disable: true
    stop_grace_period: 5m
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "wget", "--tries=1", "--spider", "http://localhost:8011/tb/ping"]
    environment:
      - JAVA_OPTS=
        -Xms2g
        -Xmx2g
        -DTimeBase.version=5.0
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/timebase-home/timebase.hprof
        -Xlog:gc=debug:file=/timebase-home/GClog-TimeBase.log:time,uptime,level,tags:filecount=5,filesize=100m
    ports:
      - 8011:8011
    volumes:
      - "./timebase-home:/timebase-home"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 9000M

  timebase-admin:
    image: "epam/timebase-ws-server:latest"
    environment:
      - JAVA_OPTS=
        -Xmx1g
        -Dserver.port=8099
        -Dserver.compression.enabled=true
        -Dserver.compression.mime-types=text/html,text/css,application/javascript,application/json
        -Dtimebase.url=dxtick://timebase:8011
    ports:
      - 80:8099
    depends_on:
      - timebase

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/epam/TimeBaseGrafanaPlugin/releases/download/1.0.7/epam-timebase-datasource.zip;epam-timebase-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=epam-timebase-datasource
    volumes:
      - "./grafana:/var/lib/grafana"
